/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginEmployeeRouteImport } from './routes/login.employee'
import { Route as LoginDeveloperRouteImport } from './routes/login.developer'
import { Route as LoginCompanyRouteImport } from './routes/login.company'
import { Route as AuthenticatedFaceVerifyRouteImport } from './routes/_authenticated/face.verify'
import { Route as AuthenticatedFaceRegisterRouteImport } from './routes/_authenticated/face.register'
import { Route as AuthenticatedFaceLockedRouteImport } from './routes/_authenticated/face.locked'
import { Route as AuthenticatedDashboardRecruiterRouteImport } from './routes/_authenticated/dashboard.recruiter'
import { Route as AuthenticatedDashboardHrLeadRouteImport } from './routes/_authenticated/dashboard.hr-lead'
import { Route as AuthenticatedDashboardDeveloperRouteImport } from './routes/_authenticated/dashboard.developer'
import { Route as AuthenticatedDashboardCompanyRouteImport } from './routes/_authenticated/dashboard.company'
import { Route as AuthenticatedDashboardRecruiterIndexRouteImport } from './routes/_authenticated/dashboard.recruiter.index'
import { Route as AuthenticatedDashboardHrLeadIndexRouteImport } from './routes/_authenticated/dashboard.hr-lead.index'
import { Route as AuthenticatedDashboardDeveloperIndexRouteImport } from './routes/_authenticated/dashboard.developer.index'
import { Route as AuthenticatedDashboardDeveloperUsersRouteImport } from './routes/_authenticated/dashboard.developer.users'
import { Route as AuthenticatedDashboardDeveloperSettingsRouteImport } from './routes/_authenticated/dashboard.developer.settings'
import { Route as AuthenticatedDashboardDeveloperRolesRouteImport } from './routes/_authenticated/dashboard.developer.roles'
import { Route as AuthenticatedDashboardDeveloperReportsRouteImport } from './routes/_authenticated/dashboard.developer.reports'
import { Route as AuthenticatedDashboardDeveloperPermissionsRouteImport } from './routes/_authenticated/dashboard.developer.permissions'
import { Route as AuthenticatedDashboardDeveloperHolidaysRouteImport } from './routes/_authenticated/dashboard.developer.holidays'
import { Route as AuthenticatedDashboardDeveloperDepartmentsRouteImport } from './routes/_authenticated/dashboard.developer.departments'
import { Route as AuthenticatedDashboardDeveloperCompaniesRouteImport } from './routes/_authenticated/dashboard.developer.companies'
import { Route as AuthenticatedDashboardDeveloperAuditLogsRouteImport } from './routes/_authenticated/dashboard.developer.audit-logs'
import { Route as AuthenticatedDashboardDeveloperAiEngineRouteImport } from './routes/_authenticated/dashboard.developer.ai-engine'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginEmployeeRoute = LoginEmployeeRouteImport.update({
  id: '/login/employee',
  path: '/login/employee',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginDeveloperRoute = LoginDeveloperRouteImport.update({
  id: '/login/developer',
  path: '/login/developer',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginCompanyRoute = LoginCompanyRouteImport.update({
  id: '/login/company',
  path: '/login/company',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFaceVerifyRoute = AuthenticatedFaceVerifyRouteImport.update({
  id: '/face/verify',
  path: '/face/verify',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFaceRegisterRoute =
  AuthenticatedFaceRegisterRouteImport.update({
    id: '/face/register',
    path: '/face/register',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFaceLockedRoute = AuthenticatedFaceLockedRouteImport.update({
  id: '/face/locked',
  path: '/face/locked',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRecruiterRoute =
  AuthenticatedDashboardRecruiterRouteImport.update({
    id: '/dashboard/recruiter',
    path: '/dashboard/recruiter',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardHrLeadRoute =
  AuthenticatedDashboardHrLeadRouteImport.update({
    id: '/dashboard/hr-lead',
    path: '/dashboard/hr-lead',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardDeveloperRoute =
  AuthenticatedDashboardDeveloperRouteImport.update({
    id: '/dashboard/developer',
    path: '/dashboard/developer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardCompanyRoute =
  AuthenticatedDashboardCompanyRouteImport.update({
    id: '/dashboard/company',
    path: '/dashboard/company',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRecruiterIndexRoute =
  AuthenticatedDashboardRecruiterIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRecruiterRoute,
  } as any)
const AuthenticatedDashboardHrLeadIndexRoute =
  AuthenticatedDashboardHrLeadIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardHrLeadRoute,
  } as any)
const AuthenticatedDashboardDeveloperIndexRoute =
  AuthenticatedDashboardDeveloperIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardDeveloperRoute,
  } as any)
const AuthenticatedDashboardDeveloperUsersRoute =
  AuthenticatedDashboardDeveloperUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedDashboardDeveloperRoute,
  } as any)
const AuthenticatedDashboardDeveloperSettingsRoute =
  AuthenticatedDashboardDeveloperSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedDashboardDeveloperRoute,
  } as any)
const AuthenticatedDashboardDeveloperRolesRoute =
  AuthenticatedDashboardDeveloperRolesRouteImport.update({
    id: '/roles',
    path: '/roles',
    getParentRoute: () => AuthenticatedDashboardDeveloperRoute,
  } as any)
const AuthenticatedDashboardDeveloperReportsRoute =
  AuthenticatedDashboardDeveloperReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedDashboardDeveloperRoute,
  } as any)
const AuthenticatedDashboardDeveloperPermissionsRoute =
  AuthenticatedDashboardDeveloperPermissionsRouteImport.update({
    id: '/permissions',
    path: '/permissions',
    getParentRoute: () => AuthenticatedDashboardDeveloperRoute,
  } as any)
const AuthenticatedDashboardDeveloperHolidaysRoute =
  AuthenticatedDashboardDeveloperHolidaysRouteImport.update({
    id: '/holidays',
    path: '/holidays',
    getParentRoute: () => AuthenticatedDashboardDeveloperRoute,
  } as any)
const AuthenticatedDashboardDeveloperDepartmentsRoute =
  AuthenticatedDashboardDeveloperDepartmentsRouteImport.update({
    id: '/departments',
    path: '/departments',
    getParentRoute: () => AuthenticatedDashboardDeveloperRoute,
  } as any)
const AuthenticatedDashboardDeveloperCompaniesRoute =
  AuthenticatedDashboardDeveloperCompaniesRouteImport.update({
    id: '/companies',
    path: '/companies',
    getParentRoute: () => AuthenticatedDashboardDeveloperRoute,
  } as any)
const AuthenticatedDashboardDeveloperAuditLogsRoute =
  AuthenticatedDashboardDeveloperAuditLogsRouteImport.update({
    id: '/audit-logs',
    path: '/audit-logs',
    getParentRoute: () => AuthenticatedDashboardDeveloperRoute,
  } as any)
const AuthenticatedDashboardDeveloperAiEngineRoute =
  AuthenticatedDashboardDeveloperAiEngineRouteImport.update({
    id: '/ai-engine',
    path: '/ai-engine',
    getParentRoute: () => AuthenticatedDashboardDeveloperRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/login/company': typeof LoginCompanyRoute
  '/login/developer': typeof LoginDeveloperRoute
  '/login/employee': typeof LoginEmployeeRoute
  '/dashboard/company': typeof AuthenticatedDashboardCompanyRoute
  '/dashboard/developer': typeof AuthenticatedDashboardDeveloperRouteWithChildren
  '/dashboard/hr-lead': typeof AuthenticatedDashboardHrLeadRouteWithChildren
  '/dashboard/recruiter': typeof AuthenticatedDashboardRecruiterRouteWithChildren
  '/face/locked': typeof AuthenticatedFaceLockedRoute
  '/face/register': typeof AuthenticatedFaceRegisterRoute
  '/face/verify': typeof AuthenticatedFaceVerifyRoute
  '/dashboard/developer/ai-engine': typeof AuthenticatedDashboardDeveloperAiEngineRoute
  '/dashboard/developer/audit-logs': typeof AuthenticatedDashboardDeveloperAuditLogsRoute
  '/dashboard/developer/companies': typeof AuthenticatedDashboardDeveloperCompaniesRoute
  '/dashboard/developer/departments': typeof AuthenticatedDashboardDeveloperDepartmentsRoute
  '/dashboard/developer/holidays': typeof AuthenticatedDashboardDeveloperHolidaysRoute
  '/dashboard/developer/permissions': typeof AuthenticatedDashboardDeveloperPermissionsRoute
  '/dashboard/developer/reports': typeof AuthenticatedDashboardDeveloperReportsRoute
  '/dashboard/developer/roles': typeof AuthenticatedDashboardDeveloperRolesRoute
  '/dashboard/developer/settings': typeof AuthenticatedDashboardDeveloperSettingsRoute
  '/dashboard/developer/users': typeof AuthenticatedDashboardDeveloperUsersRoute
  '/dashboard/developer/': typeof AuthenticatedDashboardDeveloperIndexRoute
  '/dashboard/hr-lead/': typeof AuthenticatedDashboardHrLeadIndexRoute
  '/dashboard/recruiter/': typeof AuthenticatedDashboardRecruiterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/login/company': typeof LoginCompanyRoute
  '/login/developer': typeof LoginDeveloperRoute
  '/login/employee': typeof LoginEmployeeRoute
  '/dashboard/company': typeof AuthenticatedDashboardCompanyRoute
  '/face/locked': typeof AuthenticatedFaceLockedRoute
  '/face/register': typeof AuthenticatedFaceRegisterRoute
  '/face/verify': typeof AuthenticatedFaceVerifyRoute
  '/dashboard/developer/ai-engine': typeof AuthenticatedDashboardDeveloperAiEngineRoute
  '/dashboard/developer/audit-logs': typeof AuthenticatedDashboardDeveloperAuditLogsRoute
  '/dashboard/developer/companies': typeof AuthenticatedDashboardDeveloperCompaniesRoute
  '/dashboard/developer/departments': typeof AuthenticatedDashboardDeveloperDepartmentsRoute
  '/dashboard/developer/holidays': typeof AuthenticatedDashboardDeveloperHolidaysRoute
  '/dashboard/developer/permissions': typeof AuthenticatedDashboardDeveloperPermissionsRoute
  '/dashboard/developer/reports': typeof AuthenticatedDashboardDeveloperReportsRoute
  '/dashboard/developer/roles': typeof AuthenticatedDashboardDeveloperRolesRoute
  '/dashboard/developer/settings': typeof AuthenticatedDashboardDeveloperSettingsRoute
  '/dashboard/developer/users': typeof AuthenticatedDashboardDeveloperUsersRoute
  '/dashboard/developer': typeof AuthenticatedDashboardDeveloperIndexRoute
  '/dashboard/hr-lead': typeof AuthenticatedDashboardHrLeadIndexRoute
  '/dashboard/recruiter': typeof AuthenticatedDashboardRecruiterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/login/company': typeof LoginCompanyRoute
  '/login/developer': typeof LoginDeveloperRoute
  '/login/employee': typeof LoginEmployeeRoute
  '/_authenticated/dashboard/company': typeof AuthenticatedDashboardCompanyRoute
  '/_authenticated/dashboard/developer': typeof AuthenticatedDashboardDeveloperRouteWithChildren
  '/_authenticated/dashboard/hr-lead': typeof AuthenticatedDashboardHrLeadRouteWithChildren
  '/_authenticated/dashboard/recruiter': typeof AuthenticatedDashboardRecruiterRouteWithChildren
  '/_authenticated/face/locked': typeof AuthenticatedFaceLockedRoute
  '/_authenticated/face/register': typeof AuthenticatedFaceRegisterRoute
  '/_authenticated/face/verify': typeof AuthenticatedFaceVerifyRoute
  '/_authenticated/dashboard/developer/ai-engine': typeof AuthenticatedDashboardDeveloperAiEngineRoute
  '/_authenticated/dashboard/developer/audit-logs': typeof AuthenticatedDashboardDeveloperAuditLogsRoute
  '/_authenticated/dashboard/developer/companies': typeof AuthenticatedDashboardDeveloperCompaniesRoute
  '/_authenticated/dashboard/developer/departments': typeof AuthenticatedDashboardDeveloperDepartmentsRoute
  '/_authenticated/dashboard/developer/holidays': typeof AuthenticatedDashboardDeveloperHolidaysRoute
  '/_authenticated/dashboard/developer/permissions': typeof AuthenticatedDashboardDeveloperPermissionsRoute
  '/_authenticated/dashboard/developer/reports': typeof AuthenticatedDashboardDeveloperReportsRoute
  '/_authenticated/dashboard/developer/roles': typeof AuthenticatedDashboardDeveloperRolesRoute
  '/_authenticated/dashboard/developer/settings': typeof AuthenticatedDashboardDeveloperSettingsRoute
  '/_authenticated/dashboard/developer/users': typeof AuthenticatedDashboardDeveloperUsersRoute
  '/_authenticated/dashboard/developer/': typeof AuthenticatedDashboardDeveloperIndexRoute
  '/_authenticated/dashboard/hr-lead/': typeof AuthenticatedDashboardHrLeadIndexRoute
  '/_authenticated/dashboard/recruiter/': typeof AuthenticatedDashboardRecruiterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/login/company'
    | '/login/developer'
    | '/login/employee'
    | '/dashboard/company'
    | '/dashboard/developer'
    | '/dashboard/hr-lead'
    | '/dashboard/recruiter'
    | '/face/locked'
    | '/face/register'
    | '/face/verify'
    | '/dashboard/developer/ai-engine'
    | '/dashboard/developer/audit-logs'
    | '/dashboard/developer/companies'
    | '/dashboard/developer/departments'
    | '/dashboard/developer/holidays'
    | '/dashboard/developer/permissions'
    | '/dashboard/developer/reports'
    | '/dashboard/developer/roles'
    | '/dashboard/developer/settings'
    | '/dashboard/developer/users'
    | '/dashboard/developer/'
    | '/dashboard/hr-lead/'
    | '/dashboard/recruiter/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/login/company'
    | '/login/developer'
    | '/login/employee'
    | '/dashboard/company'
    | '/face/locked'
    | '/face/register'
    | '/face/verify'
    | '/dashboard/developer/ai-engine'
    | '/dashboard/developer/audit-logs'
    | '/dashboard/developer/companies'
    | '/dashboard/developer/departments'
    | '/dashboard/developer/holidays'
    | '/dashboard/developer/permissions'
    | '/dashboard/developer/reports'
    | '/dashboard/developer/roles'
    | '/dashboard/developer/settings'
    | '/dashboard/developer/users'
    | '/dashboard/developer'
    | '/dashboard/hr-lead'
    | '/dashboard/recruiter'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/reset-password'
    | '/login/company'
    | '/login/developer'
    | '/login/employee'
    | '/_authenticated/dashboard/company'
    | '/_authenticated/dashboard/developer'
    | '/_authenticated/dashboard/hr-lead'
    | '/_authenticated/dashboard/recruiter'
    | '/_authenticated/face/locked'
    | '/_authenticated/face/register'
    | '/_authenticated/face/verify'
    | '/_authenticated/dashboard/developer/ai-engine'
    | '/_authenticated/dashboard/developer/audit-logs'
    | '/_authenticated/dashboard/developer/companies'
    | '/_authenticated/dashboard/developer/departments'
    | '/_authenticated/dashboard/developer/holidays'
    | '/_authenticated/dashboard/developer/permissions'
    | '/_authenticated/dashboard/developer/reports'
    | '/_authenticated/dashboard/developer/roles'
    | '/_authenticated/dashboard/developer/settings'
    | '/_authenticated/dashboard/developer/users'
    | '/_authenticated/dashboard/developer/'
    | '/_authenticated/dashboard/hr-lead/'
    | '/_authenticated/dashboard/recruiter/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  LoginCompanyRoute: typeof LoginCompanyRoute
  LoginDeveloperRoute: typeof LoginDeveloperRoute
  LoginEmployeeRoute: typeof LoginEmployeeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/employee': {
      id: '/login/employee'
      path: '/login/employee'
      fullPath: '/login/employee'
      preLoaderRoute: typeof LoginEmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/developer': {
      id: '/login/developer'
      path: '/login/developer'
      fullPath: '/login/developer'
      preLoaderRoute: typeof LoginDeveloperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/company': {
      id: '/login/company'
      path: '/login/company'
      fullPath: '/login/company'
      preLoaderRoute: typeof LoginCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/face/verify': {
      id: '/_authenticated/face/verify'
      path: '/face/verify'
      fullPath: '/face/verify'
      preLoaderRoute: typeof AuthenticatedFaceVerifyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/face/register': {
      id: '/_authenticated/face/register'
      path: '/face/register'
      fullPath: '/face/register'
      preLoaderRoute: typeof AuthenticatedFaceRegisterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/face/locked': {
      id: '/_authenticated/face/locked'
      path: '/face/locked'
      fullPath: '/face/locked'
      preLoaderRoute: typeof AuthenticatedFaceLockedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/recruiter': {
      id: '/_authenticated/dashboard/recruiter'
      path: '/dashboard/recruiter'
      fullPath: '/dashboard/recruiter'
      preLoaderRoute: typeof AuthenticatedDashboardRecruiterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/hr-lead': {
      id: '/_authenticated/dashboard/hr-lead'
      path: '/dashboard/hr-lead'
      fullPath: '/dashboard/hr-lead'
      preLoaderRoute: typeof AuthenticatedDashboardHrLeadRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/developer': {
      id: '/_authenticated/dashboard/developer'
      path: '/dashboard/developer'
      fullPath: '/dashboard/developer'
      preLoaderRoute: typeof AuthenticatedDashboardDeveloperRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/company': {
      id: '/_authenticated/dashboard/company'
      path: '/dashboard/company'
      fullPath: '/dashboard/company'
      preLoaderRoute: typeof AuthenticatedDashboardCompanyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/recruiter/': {
      id: '/_authenticated/dashboard/recruiter/'
      path: '/'
      fullPath: '/dashboard/recruiter/'
      preLoaderRoute: typeof AuthenticatedDashboardRecruiterIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRecruiterRoute
    }
    '/_authenticated/dashboard/hr-lead/': {
      id: '/_authenticated/dashboard/hr-lead/'
      path: '/'
      fullPath: '/dashboard/hr-lead/'
      preLoaderRoute: typeof AuthenticatedDashboardHrLeadIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardHrLeadRoute
    }
    '/_authenticated/dashboard/developer/': {
      id: '/_authenticated/dashboard/developer/'
      path: '/'
      fullPath: '/dashboard/developer/'
      preLoaderRoute: typeof AuthenticatedDashboardDeveloperIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardDeveloperRoute
    }
    '/_authenticated/dashboard/developer/users': {
      id: '/_authenticated/dashboard/developer/users'
      path: '/users'
      fullPath: '/dashboard/developer/users'
      preLoaderRoute: typeof AuthenticatedDashboardDeveloperUsersRouteImport
      parentRoute: typeof AuthenticatedDashboardDeveloperRoute
    }
    '/_authenticated/dashboard/developer/settings': {
      id: '/_authenticated/dashboard/developer/settings'
      path: '/settings'
      fullPath: '/dashboard/developer/settings'
      preLoaderRoute: typeof AuthenticatedDashboardDeveloperSettingsRouteImport
      parentRoute: typeof AuthenticatedDashboardDeveloperRoute
    }
    '/_authenticated/dashboard/developer/roles': {
      id: '/_authenticated/dashboard/developer/roles'
      path: '/roles'
      fullPath: '/dashboard/developer/roles'
      preLoaderRoute: typeof AuthenticatedDashboardDeveloperRolesRouteImport
      parentRoute: typeof AuthenticatedDashboardDeveloperRoute
    }
    '/_authenticated/dashboard/developer/reports': {
      id: '/_authenticated/dashboard/developer/reports'
      path: '/reports'
      fullPath: '/dashboard/developer/reports'
      preLoaderRoute: typeof AuthenticatedDashboardDeveloperReportsRouteImport
      parentRoute: typeof AuthenticatedDashboardDeveloperRoute
    }
    '/_authenticated/dashboard/developer/permissions': {
      id: '/_authenticated/dashboard/developer/permissions'
      path: '/permissions'
      fullPath: '/dashboard/developer/permissions'
      preLoaderRoute: typeof AuthenticatedDashboardDeveloperPermissionsRouteImport
      parentRoute: typeof AuthenticatedDashboardDeveloperRoute
    }
    '/_authenticated/dashboard/developer/holidays': {
      id: '/_authenticated/dashboard/developer/holidays'
      path: '/holidays'
      fullPath: '/dashboard/developer/holidays'
      preLoaderRoute: typeof AuthenticatedDashboardDeveloperHolidaysRouteImport
      parentRoute: typeof AuthenticatedDashboardDeveloperRoute
    }
    '/_authenticated/dashboard/developer/departments': {
      id: '/_authenticated/dashboard/developer/departments'
      path: '/departments'
      fullPath: '/dashboard/developer/departments'
      preLoaderRoute: typeof AuthenticatedDashboardDeveloperDepartmentsRouteImport
      parentRoute: typeof AuthenticatedDashboardDeveloperRoute
    }
    '/_authenticated/dashboard/developer/companies': {
      id: '/_authenticated/dashboard/developer/companies'
      path: '/companies'
      fullPath: '/dashboard/developer/companies'
      preLoaderRoute: typeof AuthenticatedDashboardDeveloperCompaniesRouteImport
      parentRoute: typeof AuthenticatedDashboardDeveloperRoute
    }
    '/_authenticated/dashboard/developer/audit-logs': {
      id: '/_authenticated/dashboard/developer/audit-logs'
      path: '/audit-logs'
      fullPath: '/dashboard/developer/audit-logs'
      preLoaderRoute: typeof AuthenticatedDashboardDeveloperAuditLogsRouteImport
      parentRoute: typeof AuthenticatedDashboardDeveloperRoute
    }
    '/_authenticated/dashboard/developer/ai-engine': {
      id: '/_authenticated/dashboard/developer/ai-engine'
      path: '/ai-engine'
      fullPath: '/dashboard/developer/ai-engine'
      preLoaderRoute: typeof AuthenticatedDashboardDeveloperAiEngineRouteImport
      parentRoute: typeof AuthenticatedDashboardDeveloperRoute
    }
  }
}

interface AuthenticatedDashboardDeveloperRouteChildren {
  AuthenticatedDashboardDeveloperAiEngineRoute: typeof AuthenticatedDashboardDeveloperAiEngineRoute
  AuthenticatedDashboardDeveloperAuditLogsRoute: typeof AuthenticatedDashboardDeveloperAuditLogsRoute
  AuthenticatedDashboardDeveloperCompaniesRoute: typeof AuthenticatedDashboardDeveloperCompaniesRoute
  AuthenticatedDashboardDeveloperDepartmentsRoute: typeof AuthenticatedDashboardDeveloperDepartmentsRoute
  AuthenticatedDashboardDeveloperHolidaysRoute: typeof AuthenticatedDashboardDeveloperHolidaysRoute
  AuthenticatedDashboardDeveloperPermissionsRoute: typeof AuthenticatedDashboardDeveloperPermissionsRoute
  AuthenticatedDashboardDeveloperReportsRoute: typeof AuthenticatedDashboardDeveloperReportsRoute
  AuthenticatedDashboardDeveloperRolesRoute: typeof AuthenticatedDashboardDeveloperRolesRoute
  AuthenticatedDashboardDeveloperSettingsRoute: typeof AuthenticatedDashboardDeveloperSettingsRoute
  AuthenticatedDashboardDeveloperUsersRoute: typeof AuthenticatedDashboardDeveloperUsersRoute
  AuthenticatedDashboardDeveloperIndexRoute: typeof AuthenticatedDashboardDeveloperIndexRoute
}

const AuthenticatedDashboardDeveloperRouteChildren: AuthenticatedDashboardDeveloperRouteChildren =
  {
    AuthenticatedDashboardDeveloperAiEngineRoute:
      AuthenticatedDashboardDeveloperAiEngineRoute,
    AuthenticatedDashboardDeveloperAuditLogsRoute:
      AuthenticatedDashboardDeveloperAuditLogsRoute,
    AuthenticatedDashboardDeveloperCompaniesRoute:
      AuthenticatedDashboardDeveloperCompaniesRoute,
    AuthenticatedDashboardDeveloperDepartmentsRoute:
      AuthenticatedDashboardDeveloperDepartmentsRoute,
    AuthenticatedDashboardDeveloperHolidaysRoute:
      AuthenticatedDashboardDeveloperHolidaysRoute,
    AuthenticatedDashboardDeveloperPermissionsRoute:
      AuthenticatedDashboardDeveloperPermissionsRoute,
    AuthenticatedDashboardDeveloperReportsRoute:
      AuthenticatedDashboardDeveloperReportsRoute,
    AuthenticatedDashboardDeveloperRolesRoute:
      AuthenticatedDashboardDeveloperRolesRoute,
    AuthenticatedDashboardDeveloperSettingsRoute:
      AuthenticatedDashboardDeveloperSettingsRoute,
    AuthenticatedDashboardDeveloperUsersRoute:
      AuthenticatedDashboardDeveloperUsersRoute,
    AuthenticatedDashboardDeveloperIndexRoute:
      AuthenticatedDashboardDeveloperIndexRoute,
  }

const AuthenticatedDashboardDeveloperRouteWithChildren =
  AuthenticatedDashboardDeveloperRoute._addFileChildren(
    AuthenticatedDashboardDeveloperRouteChildren,
  )

interface AuthenticatedDashboardHrLeadRouteChildren {
  AuthenticatedDashboardHrLeadIndexRoute: typeof AuthenticatedDashboardHrLeadIndexRoute
}

const AuthenticatedDashboardHrLeadRouteChildren: AuthenticatedDashboardHrLeadRouteChildren =
  {
    AuthenticatedDashboardHrLeadIndexRoute:
      AuthenticatedDashboardHrLeadIndexRoute,
  }

const AuthenticatedDashboardHrLeadRouteWithChildren =
  AuthenticatedDashboardHrLeadRoute._addFileChildren(
    AuthenticatedDashboardHrLeadRouteChildren,
  )

interface AuthenticatedDashboardRecruiterRouteChildren {
  AuthenticatedDashboardRecruiterIndexRoute: typeof AuthenticatedDashboardRecruiterIndexRoute
}

const AuthenticatedDashboardRecruiterRouteChildren: AuthenticatedDashboardRecruiterRouteChildren =
  {
    AuthenticatedDashboardRecruiterIndexRoute:
      AuthenticatedDashboardRecruiterIndexRoute,
  }

const AuthenticatedDashboardRecruiterRouteWithChildren =
  AuthenticatedDashboardRecruiterRoute._addFileChildren(
    AuthenticatedDashboardRecruiterRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardCompanyRoute: typeof AuthenticatedDashboardCompanyRoute
  AuthenticatedDashboardDeveloperRoute: typeof AuthenticatedDashboardDeveloperRouteWithChildren
  AuthenticatedDashboardHrLeadRoute: typeof AuthenticatedDashboardHrLeadRouteWithChildren
  AuthenticatedDashboardRecruiterRoute: typeof AuthenticatedDashboardRecruiterRouteWithChildren
  AuthenticatedFaceLockedRoute: typeof AuthenticatedFaceLockedRoute
  AuthenticatedFaceRegisterRoute: typeof AuthenticatedFaceRegisterRoute
  AuthenticatedFaceVerifyRoute: typeof AuthenticatedFaceVerifyRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardCompanyRoute: AuthenticatedDashboardCompanyRoute,
  AuthenticatedDashboardDeveloperRoute:
    AuthenticatedDashboardDeveloperRouteWithChildren,
  AuthenticatedDashboardHrLeadRoute:
    AuthenticatedDashboardHrLeadRouteWithChildren,
  AuthenticatedDashboardRecruiterRoute:
    AuthenticatedDashboardRecruiterRouteWithChildren,
  AuthenticatedFaceLockedRoute: AuthenticatedFaceLockedRoute,
  AuthenticatedFaceRegisterRoute: AuthenticatedFaceRegisterRoute,
  AuthenticatedFaceVerifyRoute: AuthenticatedFaceVerifyRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  LoginCompanyRoute: LoginCompanyRoute,
  LoginDeveloperRoute: LoginDeveloperRoute,
  LoginEmployeeRoute: LoginEmployeeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
