/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginEmployeeRouteImport } from './routes/login.employee'
import { Route as LoginDeveloperRouteImport } from './routes/login.developer'
import { Route as LoginCompanyRouteImport } from './routes/login.company'
import { Route as AuthenticatedFaceVerifyRouteImport } from './routes/_authenticated/face.verify'
import { Route as AuthenticatedFaceRegisterRouteImport } from './routes/_authenticated/face.register'
import { Route as AuthenticatedFaceLockedRouteImport } from './routes/_authenticated/face.locked'
import { Route as AuthenticatedDashboardDeveloperRouteImport } from './routes/_authenticated/dashboard.developer'
import { Route as AuthenticatedDashboardCompanyRouteImport } from './routes/_authenticated/dashboard.company'
import { Route as AuthenticatedDashboardDeveloperIndexRouteImport } from './routes/_authenticated/dashboard.developer.index'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginEmployeeRoute = LoginEmployeeRouteImport.update({
  id: '/login/employee',
  path: '/login/employee',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginDeveloperRoute = LoginDeveloperRouteImport.update({
  id: '/login/developer',
  path: '/login/developer',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginCompanyRoute = LoginCompanyRouteImport.update({
  id: '/login/company',
  path: '/login/company',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFaceVerifyRoute = AuthenticatedFaceVerifyRouteImport.update({
  id: '/face/verify',
  path: '/face/verify',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFaceRegisterRoute =
  AuthenticatedFaceRegisterRouteImport.update({
    id: '/face/register',
    path: '/face/register',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFaceLockedRoute = AuthenticatedFaceLockedRouteImport.update({
  id: '/face/locked',
  path: '/face/locked',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardDeveloperRoute =
  AuthenticatedDashboardDeveloperRouteImport.update({
    id: '/dashboard/developer',
    path: '/dashboard/developer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardCompanyRoute =
  AuthenticatedDashboardCompanyRouteImport.update({
    id: '/dashboard/company',
    path: '/dashboard/company',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardDeveloperIndexRoute =
  AuthenticatedDashboardDeveloperIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardDeveloperRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/login/company': typeof LoginCompanyRoute
  '/login/developer': typeof LoginDeveloperRoute
  '/login/employee': typeof LoginEmployeeRoute
  '/dashboard/company': typeof AuthenticatedDashboardCompanyRoute
  '/dashboard/developer': typeof AuthenticatedDashboardDeveloperRouteWithChildren
  '/face/locked': typeof AuthenticatedFaceLockedRoute
  '/face/register': typeof AuthenticatedFaceRegisterRoute
  '/face/verify': typeof AuthenticatedFaceVerifyRoute
  '/dashboard/developer/': typeof AuthenticatedDashboardDeveloperIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/login/company': typeof LoginCompanyRoute
  '/login/developer': typeof LoginDeveloperRoute
  '/login/employee': typeof LoginEmployeeRoute
  '/dashboard/company': typeof AuthenticatedDashboardCompanyRoute
  '/face/locked': typeof AuthenticatedFaceLockedRoute
  '/face/register': typeof AuthenticatedFaceRegisterRoute
  '/face/verify': typeof AuthenticatedFaceVerifyRoute
  '/dashboard/developer': typeof AuthenticatedDashboardDeveloperIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/login/company': typeof LoginCompanyRoute
  '/login/developer': typeof LoginDeveloperRoute
  '/login/employee': typeof LoginEmployeeRoute
  '/_authenticated/dashboard/company': typeof AuthenticatedDashboardCompanyRoute
  '/_authenticated/dashboard/developer': typeof AuthenticatedDashboardDeveloperRouteWithChildren
  '/_authenticated/face/locked': typeof AuthenticatedFaceLockedRoute
  '/_authenticated/face/register': typeof AuthenticatedFaceRegisterRoute
  '/_authenticated/face/verify': typeof AuthenticatedFaceVerifyRoute
  '/_authenticated/dashboard/developer/': typeof AuthenticatedDashboardDeveloperIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/login/company'
    | '/login/developer'
    | '/login/employee'
    | '/dashboard/company'
    | '/dashboard/developer'
    | '/face/locked'
    | '/face/register'
    | '/face/verify'
    | '/dashboard/developer/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/login/company'
    | '/login/developer'
    | '/login/employee'
    | '/dashboard/company'
    | '/face/locked'
    | '/face/register'
    | '/face/verify'
    | '/dashboard/developer'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/reset-password'
    | '/login/company'
    | '/login/developer'
    | '/login/employee'
    | '/_authenticated/dashboard/company'
    | '/_authenticated/dashboard/developer'
    | '/_authenticated/face/locked'
    | '/_authenticated/face/register'
    | '/_authenticated/face/verify'
    | '/_authenticated/dashboard/developer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  LoginCompanyRoute: typeof LoginCompanyRoute
  LoginDeveloperRoute: typeof LoginDeveloperRoute
  LoginEmployeeRoute: typeof LoginEmployeeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/employee': {
      id: '/login/employee'
      path: '/login/employee'
      fullPath: '/login/employee'
      preLoaderRoute: typeof LoginEmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/developer': {
      id: '/login/developer'
      path: '/login/developer'
      fullPath: '/login/developer'
      preLoaderRoute: typeof LoginDeveloperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/company': {
      id: '/login/company'
      path: '/login/company'
      fullPath: '/login/company'
      preLoaderRoute: typeof LoginCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/face/verify': {
      id: '/_authenticated/face/verify'
      path: '/face/verify'
      fullPath: '/face/verify'
      preLoaderRoute: typeof AuthenticatedFaceVerifyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/face/register': {
      id: '/_authenticated/face/register'
      path: '/face/register'
      fullPath: '/face/register'
      preLoaderRoute: typeof AuthenticatedFaceRegisterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/face/locked': {
      id: '/_authenticated/face/locked'
      path: '/face/locked'
      fullPath: '/face/locked'
      preLoaderRoute: typeof AuthenticatedFaceLockedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/developer': {
      id: '/_authenticated/dashboard/developer'
      path: '/dashboard/developer'
      fullPath: '/dashboard/developer'
      preLoaderRoute: typeof AuthenticatedDashboardDeveloperRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/company': {
      id: '/_authenticated/dashboard/company'
      path: '/dashboard/company'
      fullPath: '/dashboard/company'
      preLoaderRoute: typeof AuthenticatedDashboardCompanyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/developer/': {
      id: '/_authenticated/dashboard/developer/'
      path: '/'
      fullPath: '/dashboard/developer/'
      preLoaderRoute: typeof AuthenticatedDashboardDeveloperIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardDeveloperRoute
    }
  }
}

interface AuthenticatedDashboardDeveloperRouteChildren {
  AuthenticatedDashboardDeveloperIndexRoute: typeof AuthenticatedDashboardDeveloperIndexRoute
}

const AuthenticatedDashboardDeveloperRouteChildren: AuthenticatedDashboardDeveloperRouteChildren =
  {
    AuthenticatedDashboardDeveloperIndexRoute:
      AuthenticatedDashboardDeveloperIndexRoute,
  }

const AuthenticatedDashboardDeveloperRouteWithChildren =
  AuthenticatedDashboardDeveloperRoute._addFileChildren(
    AuthenticatedDashboardDeveloperRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardCompanyRoute: typeof AuthenticatedDashboardCompanyRoute
  AuthenticatedDashboardDeveloperRoute: typeof AuthenticatedDashboardDeveloperRouteWithChildren
  AuthenticatedFaceLockedRoute: typeof AuthenticatedFaceLockedRoute
  AuthenticatedFaceRegisterRoute: typeof AuthenticatedFaceRegisterRoute
  AuthenticatedFaceVerifyRoute: typeof AuthenticatedFaceVerifyRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardCompanyRoute: AuthenticatedDashboardCompanyRoute,
  AuthenticatedDashboardDeveloperRoute:
    AuthenticatedDashboardDeveloperRouteWithChildren,
  AuthenticatedFaceLockedRoute: AuthenticatedFaceLockedRoute,
  AuthenticatedFaceRegisterRoute: AuthenticatedFaceRegisterRoute,
  AuthenticatedFaceVerifyRoute: AuthenticatedFaceVerifyRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  LoginCompanyRoute: LoginCompanyRoute,
  LoginDeveloperRoute: LoginDeveloperRoute,
  LoginEmployeeRoute: LoginEmployeeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
